spring:
  application:
    name: stock-quotes

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create # use update for dev, create-drop for tests and validate for homolog and prod
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
        timeout: 3000ms

  cache:
    type: redis
    cache-names:
      - quotes
      - symbols
    redis:
      time-to-live: 600000
      cache-null-values: false

server:
  port: 8080

finnhub:
#  base-url: ${FINNHUB_BASE_URL}
  base-url: http://nginx:20000/api/v1
  token: ${FINNHUB_TOKEN}
  refresh-rate-ms: 60000
  symbols:
    - AAPL
    - MSFT
    - NVDA
    - TSLA
    - GOOGL
    - AMZN
    - META
    - JPM
    - NFLX
    - AMD
    - INTC

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, circuitbreakers
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    tech.stockquotes: ${APP_LOG_LEVEL:DEBUG}
    org.hibernate: ${APP_LOG_LEVEL_HIBERNATE:WARN}